<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3ac47d19-7cb3-465e-9129-f1bc2fa464a9</elementGuidId>
    <imagePath></imagePath>
    <name>input_email</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[1]/div[3]/div[1]/form[1]/input[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'email') and equals(@type,'email')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>email</value>
        <webElementGuid>061ced50-666e-4c9e-9b51-7edc05a8ca0e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>email</value>
        <webElementGuid>061ced50-666e-4c9e-9b51-7edc05a8ca0e</webElementGuid>
    </webElementProperties>
</WebElementEntity>