<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>69ccf509-259e-4834-ab47-8c9c3d25a210</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_3_mast_harbour</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[4]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'(3)
            MAST &amp; HARBOUR')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>(3)
        MAST &amp; HARBOUR</value>
        <webElementGuid>12273d43-1db8-4173-b94c-1e8e7bc790b0</webElementGuid>
    </webElementProperties>
</WebElementEntity>