<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>93718890-4bcf-4245-b4f1-c97edecbe777</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_view_product</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'View Product')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>View Product</value>
        <webElementGuid>12273d43-1db8-4173-b94c-1e8e7bc790b0</webElementGuid>
    </webElementProperties>
</WebElementEntity>