<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f67ac495-98a5-437e-bd22-408ac9fa8bbe</elementGuidId>
    <imagePath></imagePath>
    <name>input_name</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[1]/div[3]/div[1]/form[1]/input[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'name') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>name</value>
        <webElementGuid>061ced50-666e-4c9e-9b51-7edc05a8ca0e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>061ced50-666e-4c9e-9b51-7edc05a8ca0e</webElementGuid>
    </webElementProperties>
</WebElementEntity>